baseURL = "https://a1sareru.github.io/ggk/"
locale = "ja"
title = "ごがく"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false
